- sonarQuest-frontend/src/app/app.module.ts
- sonarQuest-frontend/src/app/pages/my-avatar-page/components/my-avatar-edit/my-avatar-edit.component.html
- sonarQuest-frontend/src/app/pages/my-avatar-page/components/my-avatar-edit/my-avatar-edit.component.spec.ts
- sonarQuest-frontend/src/app/pages/my-avatar-page/components/my-avatar-edit/my-avatar-edit.component.ts
- sonarQuest-frontend/src/app/pages/my-avatar-page/my-avatar-page.component.html
- sonarQuest-frontend/src/app/pages/my-avatar-page/my-avatar-page.component.ts
Fixes #24 .
I added the functionality to edit an avatar. At the moment it is the same functionality like the admin developer editing function. When authentication is added, we'll have to modify it.
> Issue24 dev

- .gitignore
- sonarQuest-backend/pom.xml
> Dropped spring repo reference, ignore logfiles.

- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/controllers/AdventureController.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/controllers/ArtefactController.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/controllers/AvatarClassController.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/controllers/AvatarRaceController.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/controllers/DeveloperController.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/controllers/LevelController.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/controllers/QuestController.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/controllers/SkillController.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/controllers/TaskController.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/controllers/WorldController.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/dtos/AdventureDto.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/services/AdventureService.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/services/ArtefactService.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/services/DeveloperService.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/services/ExternalRessourceService.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/services/GratificationService.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/services/LevelService.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/services/QuestService.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/services/SkillService.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/services/SpecialTaskService.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/services/StandardTaskEvaluationService.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/services/StandardTaskService.java
- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/services/WorldService.java
- Removed all redundant this qualifiers
- Changed iterator loops to foreach
- Removed redundant initialisations
- Changed rendundant type declarations for collections with diamonds <>
- StandardTaskService: Changed (altho not a bug in this case) a == string compare with Objects.equals (also the rest of the class Strings were compared with Objects.equals)
- Changed simple lambdas to method references
- Removed rendundant return statements in void methods
- Removed some redundant local variables
what did you change? A: Hi i just plowed trough the code and saw many redundant easy to fix code lines, and code written in 1.4 1.5 1.6 and 1.7 manner which could be changed to be all in 1.8 …
> Code cleanup 1st iteration

- CONTRIBUTING.md
- docker-compose.yml
- installation.md
- sonarQuest-backend/Docker/Dockerfile
- sonarQuest-frontend/Docker/Dockerfile
- sonarQuest-frontend/package.json
Update installation documentation with docker instructions
Dockerized SonarQuest client and server.
Having the application run in docker containers comes with multiple advantages. E.g. independency from the development system. This also makes the project cloud-ready, which is an important requirement to be able to use it easily across multiple users.
No changes to functionality were made.
P.S.
Greetings from JAX :)
> Dockerize SQuest backend and frontend

- sonarQuest-frontend/src/app/pages/admin-page/components/admin-developer/components/admin-developer-create/admin-developer-create.component.ts
Fixed the custom validator that checked whether a name is already taken
> Fix for #75

- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-task/components/gamemaster-special-task/components/gamemaster-special-task-create/gamemaster-special-task-create.component.ts
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-task/components/gamemaster-standard-task/components/gamemaster-standard-task-create/gamemaster-standard-task-create.component.ts
- sonarQuest-frontend/src/app/services/standard-task.service.ts
No refresh needed now after insertion of new task
> Show data immediately after saving them

- sonarQuest-backend/src/main/java/com/viadee/sonarQuest/services/DeveloperService.java
- sonarQuest-frontend/src/app/pages/admin-page/components/admin-developer/components/admin-developer-edit/admin-developer-edit.component.html
- sonarQuest-frontend/src/app/pages/my-avatar-page/components/my-avatar-edit/my-avatar-edit.component.html
- sonarQuest-frontend/src/app/pages/my-avatar-page/components/my-avatar-edit/my-avatar-edit.component.ts
- sonarQuest-frontend/src/app/pages/my-avatar-page/my-avatar-page.component.ts
- sonarQuest-frontend/src/app/services/developer.service.ts
Updating the developer works properly now. Changes are displayed immediately
> #87 Fixed edit developer component

- sonarQuest-frontend/Docker/Dockerfile_nginx
- sonarQuest-frontend/Docker/README.md
- sonarQuest-frontend/Docker/nginx.conf
> added Dockerfile for the frontend served by nginx

- sonarQuest-frontend/src/app/app.component.ts
- sonarQuest-frontend/src/app/login/login.component.css
- sonarQuest-frontend/src/app/login/login.component.html
- sonarQuest-frontend/src/app/login/login.component.ts
- sonarQuest-frontend/src/environments/environment.prod.ts
- sonarQuest-frontend/src/environments/environment.ts
> Login Dialog rework

- sonarQuest-frontend/src/app/app.component.css
- sonarQuest-frontend/src/app/app.component.html
> improved login status styling

- sonarQuest-backend/Docker/Dockerfile2
- sonarQuest-backend/Docker/README.md
> added another Dockerfile for the backend which allows external configuration

- sonarQuest-frontend/src/app/pages/admin-page/components/admin-developer/components/admin-developer-edit/admin-developer-edit.component.html
When an admin edits a user, he can see his user role
> show user role when admin edit user

- sonarQuest-frontend/src/app/pages/my-avatar-page/components/my-avatar-edit/my-avatar-edit.component.html
fix(my-avatar-edit): translation of placeholders
- edit user details are now translated
- Issue #175
> Translation of edit user details placeholders

- sonarQuest-frontend/src/app/pages/quest-page/components/available-quests/available-quests.component.css
- sonarQuest-frontend/src/app/pages/quest-page/components/available-quests/available-quests.component.html
- sonarQuest-frontend/src/app/pages/quest-page/components/participated-quests/participated-quests.component.css
- sonarQuest-frontend/src/app/pages/quest-page/components/participated-quests/participated-quests.component.html
Fixing Cardlayout for Questoverview
> #183 SonarQuest FE / Quests / Rework quests presentation layout

- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-adventure/gamemaster-adventure.component.html
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-adventure/gamemaster-adventure.component.ts
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-quest/gamemaster-quest.component.ts
- sonarQuest-frontend/src/app/pages/gamemaster-page/gamemaster-page.component.html
- sonarQuest-frontend/src/app/pages/gamemaster-page/gamemaster-page.component.ts
- sonarQuest-frontend/src/app/pages/my-avatar-page/components/my-avatar-edit/my-avatar-edit.component.html
- If no free quests are available the new adventure button is disabled
- solves Issue #188 
- replaced var with let
> Usability improvement: "New adventure" button disabled depending on state

- sonarQuest-backend/src/main/java/com/viadee/sonarquest/controllers/UserController.java
Useful - I am merging this into master.
> Remove superfluous IOException from UserController

- sonarQuest-backend/src/main/java/com/viadee/sonarquest/entities/User.java
- sonarQuest-backend/src/main/java/com/viadee/sonarquest/repositories/UserRepository.java
- sonarQuest-backend/src/main/java/com/viadee/sonarquest/services/UserService.java
- sonarQuest-backend/src/main/resources/db/schema/V0_0_10__SQUser_mail.sql
- sonarQuest-frontend/src/app/Interfaces/User.ts
- sonarQuest-frontend/src/app/pages/admin-page/components/admin-developer/admin-developer.component.ts
- sonarQuest-frontend/src/app/pages/admin-page/components/admin-developer/components/admin-developer-create/admin-developer-create.component.html
- sonarQuest-frontend/src/app/pages/admin-page/components/admin-developer/components/admin-developer-create/admin-developer-create.component.ts
- sonarQuest-frontend/src/app/pages/admin-page/components/admin-developer/components/admin-developer-edit/admin-developer-edit.component.html
- sonarQuest-frontend/src/app/pages/admin-page/components/admin-developer/components/admin-developer-edit/admin-developer-edit.component.ts
- sonarQuest-frontend/src/app/pages/my-avatar-page/components/my-avatar-edit/my-avatar-edit.component.html
- sonarQuest-frontend/src/app/services/user.service.ts
- sonarQuest-frontend/src/assets/i18n/de.json
- sonarQuest-frontend/src/assets/i18n/en.json
Now users and administrators have the option to add and change the email by themselves or in the admin panel.
> Add email to user

- sonarQuest-frontend/src/app/pages/event-page/event-page.component.css
- sonarQuest-frontend/src/app/pages/event-page/event-page.component.html
- sonarQuest-frontend/src/app/pages/event-page/event-page.component.ts
- sonarQuest-frontend/src/app/services/websocket.service.ts
> on new message, Story scrolls down

- sonarQuest-frontend/src/app/app.component.html
- sonarQuest-frontend/src/app/app.component.ts
- sonarQuest-frontend/src/app/login/login.component.html
- sonarQuest-frontend/src/app/login/login.component.ts
- sonarQuest-frontend/src/app/pages/empty-page/empty-page.component.html
- sonarQuest-frontend/src/assets/i18n/de.json
- sonarQuest-frontend/src/assets/i18n/en.json
- sonarQuest-frontend/src/styles.css
- sonarQuest-frontend/src/theme.scss
Login page looks better
After login, the correct design is always displayed
Toolip for login window
> Designupdate

- sonarQuest-backend/src/main/java/com/viadee/sonarquest/entities/Artefact.java
Fixes 173.
Artifacts with skills can now be created.
> Changed CascadeType from skills in Artefact to MERGE and PERSIST

- sonarQuest-backend/src/main/java/com/viadee/sonarquest/controllers/ArtefactController.java
- sonarQuest-backend/src/main/java/com/viadee/sonarquest/entities/Artefact.java
- sonarQuest-backend/src/main/java/com/viadee/sonarquest/entities/Skill.java
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-marketplace/gamemaster-marketplace.component.ts
- sonarQuest-frontend/src/app/services/artefact.service.ts
- sonarQuest-frontend/src/assets/i18n/de.json
- sonarQuest-frontend/src/assets/i18n/en.json
When an artifact is deleted, the associated user is no longer deleted. In the FE, a pop-up is generated informing the user that there is still one user assigned.
> Fixed #197 - Deleting artefacts

- sonarQuest-frontend/package.json
- sonarQuest-frontend/src/app/app.module.ts
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-adventure/gamemaster-adventure.component.html
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-adventure/gamemaster-adventure.component.ts
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-marketplace/gamemaster-marketplace.component.html
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-marketplace/gamemaster-marketplace.component.ts
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-quest/gamemaster-quest.component.html
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-quest/gamemaster-quest.component.ts
- sonarQuest-frontend/src/assets/i18n/de.json
- sonarQuest-frontend/src/assets/i18n/en.json
The method confirm (), which shows a default system popup, has been replaced by SweetAlert
> Uses SweetAlert2 instead of confirm()

- sonarQuest-backend/src/main/java/com/viadee/sonarquest/controllers/ArtefactController.java
- sonarQuest-backend/src/main/java/com/viadee/sonarquest/controllers/SkillController.java
- sonarQuest-backend/src/main/java/com/viadee/sonarquest/entities/Artefact.java
- sonarQuest-backend/src/main/java/com/viadee/sonarquest/entities/Level.java
- sonarQuest-backend/src/main/java/com/viadee/sonarquest/entities/User.java
- sonarQuest-backend/src/main/java/com/viadee/sonarquest/repositories/ArtefactRepository.java
- sonarQuest-backend/src/main/java/com/viadee/sonarquest/services/ArtefactService.java
- sonarQuest-backend/src/main/resources/db/data/V0_0_13__data_insert_on_marketplace.sql
- sonarQuest-backend/src/main/resources/db/schema/V0_0_12__schema_alter_artefact.sql
- sonarQuest-frontend/src/app/Interfaces/Artefact.ts
- sonarQuest-frontend/src/app/app.module.ts
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-marketplace/components/gamemaster-artefact-create/gamemaster-artefact-create.component.html
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-marketplace/components/gamemaster-artefact-create/gamemaster-artefact-create.component.ts
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-marketplace/components/gamemaster-artefact-edit/components/gamemaster-skill-edit/gamemaster-skill-edit.component.html
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-marketplace/components/gamemaster-artefact-edit/components/gamemaster-skill-edit/gamemaster-skill-edit.component.spec.ts
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-marketplace/components/gamemaster-artefact-edit/components/gamemaster-skill-edit/gamemaster-skill-edit.component.ts
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-marketplace/components/gamemaster-artefact-edit/gamemaster-artefact-edit.component.html
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-marketplace/components/gamemaster-artefact-edit/gamemaster-artefact-edit.component.ts
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-marketplace/gamemaster-marketplace.component.html
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-marketplace/gamemaster-marketplace.component.ts
- sonarQuest-frontend/src/app/pages/gamemaster-page/components/gamemaster-quest/gamemaster-quest.component.ts
- sonarQuest-frontend/src/app/services/artefact.service.ts
- sonarQuest-frontend/src/app/services/skill.service.ts
- sonarQuest-frontend/src/app/services/translate.service.mock.module.ts
- sonarQuest-frontend/src/assets/i18n/de.json
- sonarQuest-frontend/src/assets/i18n/en.json
If you delete an artefact that still has users associated with it, you can pay the purchase price of the artefact to users and remove the artefact. Alternatively, you can remove the artefact from the marketplace.
It is also possible to add, edit, and remove artefact skills. It doesn't matter if the artefact is new or already exists.
> Optimized artefact deleting

- sonarQuest-frontend/src/app/layouts/main-layout/main-layout.component.html
- sonarQuest-frontend/src/app/layouts/main-layout/main-layout.component.ts
- sonarQuest-frontend/src/app/pages/event-page/event-page.component.css
> fixes background issue

- sonarQuest-frontend/src/app/layouts/main-layout/main-layout.component.ts
> error message removed

- sonarQuest-backend/src/main/java/com/viadee/sonarquest/services/SonarConfigService.java
> Fixed issue #253 where basic auth is not saved when updating config.

- sonarQuest-backend/src/main/java/com/viadee/sonarquest/entities/SonarConfig.java
- sonarQuest-backend/src/main/java/com/viadee/sonarquest/externalressources/SonarQubeApiCall.java
- sonarQuest-backend/src/main/java/com/viadee/sonarquest/services/ExternalRessourceService.java
- sonarQuest-backend/src/main/java/com/viadee/sonarquest/services/SonarConfigService.java
- sonarQuest-backend/src/main/resources/db/data/V0_0_2__data.sql
- sonarQuest-backend/src/main/resources/db/schema/V0_0_1__schema.sql
- sonarQuest-frontend/src/app/Interfaces/SonarQubeConfig.ts
- sonarQuest-frontend/src/app/pages/admin-page/components/admin-sonar-qube/admin-sonar-qube.component.html
- sonarQuest-frontend/src/app/pages/admin-page/components/admin-sonar-qube/admin-sonar-qube.component.ts
> Update spring version

- sonarQuest-backend/Dockerfile
- sonarQuest-backend/pom.xml
> Altered output path for docker build and changed Dockerfile for JDK11

- docker-compose.yml
> Corrected port mapping in docker compose

- README.md
> Replaced build patch with GitHub Action status

- .github/workflows/sonarquest-ci.yml
- sonarQuest-backend/Dockerfile
- sonarQuest-frontend/Dockerfile
> Added artifact upload

- .github/workflows/sonarquest-ci.yml
> Enable push of Docker image to GHCR

- sonarQuest-backend/src/main/java/com/viadee/sonarquest/controllers/UserController.java
- sonarQuest-backend/src/main/java/com/viadee/sonarquest/entities/UserDto.java
- sonarQuest-backend/src/main/java/com/viadee/sonarquest/services/WizardService.java
- sonarQuest-backend/src/main/java/com/viadee/sonarquest/services/WorldService.java
- sonarQuest-frontend/src/app/pages/login-page/login-page.component.scss
- what did you change? 
_user are returned as DTO without the password_
- why did you change it? why should it be in master?
_To solve the security problem of sending the password to the frontend_ 
- which issues are solved by this?
_issue #270_
Later, in a larger pull request, DTOs should be used consistently. Possibly with ModdelMapper
> Fix #270 - Password is returned
